"""Implementation-status constants shared by catalog and capability matrix."""

from __future__ import annotations


DIRECT_MUTATION_TOOLS = {
    "create_search_campaign",
    "create_display_campaign",
    "create_shopping_campaign",
    "create_pmax_campaign",
    "create_demand_gen_campaign",
    "create_app_campaign",
    "create_budget",
    "create_shared_budget",
    "update_budget",
    "update_shared_budget",
    "remove_budget",
    "link_budget_to_campaign",
    "update_campaign",
    "update_network_settings",
    "bulk_pause_campaigns",
    "bulk_enable_campaigns",
    "pause_campaign",
    "enable_campaign",
    "remove_campaign",
    "create_ad_group",
    "update_ad_group",
    "pause_ad_group",
    "enable_ad_group",
    "remove_ad_group",
    "create_responsive_search_ad",
    "pause_ad",
    "enable_ad",
    "remove_ad",
    "add_keywords",
    "bulk_add_keywords",
    "update_keyword_bid",
    "bulk_update_bids",
    "pause_keyword",
    "enable_keyword",
    "remove_keywords",
    "bulk_add_negative_keywords",
    "create_sitelink",
    "create_callout",
    "create_text_asset",
    "create_video_asset",
    "create_label",
    "update_label",
    "remove_label",
    "apply_campaign_label",
    "remove_campaign_label",
    "apply_ad_group_label",
    "remove_ad_group_label",
    "apply_ad_label",
    "remove_ad_label",
    "apply_keyword_label",
    "remove_keyword_label",
    "apply_label_to_campaign",
    "apply_label_to_ad_group",
    "apply_label_to_ad",
    "apply_label_to_keyword",
    "remove_label_from_campaign",
    "remove_label_from_ad_group",
    "remove_label_from_ad",
    "remove_label_from_keyword",
}

DIRECT_NEGATIVE_KEYWORD_TOOLS = {
    "add_negative_keywords_ad_group",
    "add_negative_keywords_campaign",
    "remove_negative_keywords_ad_group",
    "remove_negative_keywords_campaign",
    "create_shared_negative_keyword_list",
    "add_keywords_to_shared_list",
    "remove_keywords_from_shared_list",
    "apply_shared_list_to_campaign",
    "remove_shared_list_from_campaign",
    "bulk_add_negative_keywords",
}
